### ISSUE TITLE
ValueError: some of the strides of a given numpy array are negative. This is currently not supported, but will be added in future releases.

### ISSUE THREAD

**Issue by HaodaY** [DevSinghSachan/ssl_text_classification#2]
I run the script run_aclImdbSimple_pretrained_mixed.sh, and it shows that:
{
    "vocab_size": 80000,
    "tok": true,
    "max_seq_length": 1000,
    "input": "data",
    "output": "temp/aclImdbSimple_pretrained_mixed/data",
    "save_data": "demo",
    "aclImdb_tok_dev": "aclImdb_tok/test.txt",
    "aclImdb_tok_test": "aclImdb_tok/test.txt",
    "aclImdb_tok_train": "aclImdb_tok/train.txt",
    "aclImdb_tok_unlabel": "aclImdb_tok/test.txt",
    "elec_dev": "elec/dev.txt",
    "elec_test": "elec/test.txt",
    "elec_train": "elec/train.txt",
    "elec_unlabel": "elec/test.txt",
    "agnews_dev": "agnews/dev.txt",
    "agnews_test": "agnews/test.txt",
    "agnews_train": "agnews/train.txt",
    "agnews_unlabel": "agnews/test.txt",
    "dbpedia_dev": "dbpedia/dev.txt",
    "dbpedia_test": "dbpedia/test.txt",
    "dbpedia_train": "dbpedia/train.txt",
    "dbpedia_unlabel": "dbpedia/train.txt",
    "rcv1_dev": "rcv1/dev.txt",
    "rcv1_test": "rcv1/test.txt",
    "rcv1_train": "rcv1/train.txt",
    "rcv1_unlabel": "rcv1/unlabel.txt",
    "imdb_dev": "imdb/dev.txt",
    "imdb_test": "imdb/test.txt",
    "imdb_train": "imdb/train.txt",
    "imdb_unlabel": "imdb/test.txt",
    "arxiv_dev": "arxiv/dev.txt",
    "arxiv_test": "arxiv/test.txt",
    "arxiv_train": "arxiv/train.txt",
    "arxiv_unlabel": "arxiv/test.txt",
    "quora_iq_dev": "quora_iq/test.txt",
    "quora_iq_test": "quora_iq/test.txt",
    "quora_iq_train": "quora_iq/train.txt",
    "quora_iq_unlabel": "quora_iq/test.txt",
    "corpus": "aclImdb_tok",
    "train_filename": "aclImdb_tok/train.txt",
    "dev_filename": "aclImdb_tok/test.txt",
    "test_filename": "aclImdb_tok/test.txt",
    "unlabel_filename": "aclImdb_tok/test.txt"
}
100% (25000 of 25000) |###############################################################################################| Elapsed Time: 0:00:06 Time:  0:00:06
100% (25000 of 25000) |###############################################################################################| Elapsed Time: 0:00:06 Time:  0:00:06
100% (25000 of 25000) |###############################################################################################| Elapsed Time: 0:00:06 Time:  0:00:06
100% (25000 of 25000) |###############################################################################################| Elapsed Time: 0:00:03 Time:  0:00:03
100% (25000 of 25000) |###############################################################################################| Elapsed Time: 0:00:06 Time:  0:00:06
# of tokens: 6694979
# of unknown: 9082 (0.14 %)
100% (25000 of 25000) |###############################################################################################| Elapsed Time: 0:00:06 Time:  0:00:06
# of tokens: 6848132
# of unknown: 10760 (0.16 %)
Vocab: 114419
Original training data size: 25000
Filtered training data size: 24660
100% (25000 of 25000) |###############################################################################################| Elapsed Time: 0:00:06 Time:  0:00:06
# of tokens: 6694979
# of unknown: 9082 (0.14 %)
100% (25000 of 25000) |###############################################################################################| Elapsed Time: 0:00:06 Time:  0:00:06
# of tokens: 6694979
# of unknown: 9082 (0.14 %)
Percentage of Pre-trained word vectors: 76.32211433415779
{
    "model": "LSTMEncoder",
    "d_units": 300,
    "d_proj": 200,
    "d_hidden": 512,
    "projection": false,
    "d_down_proj": 100,
    "down_projection": false,
    "num_discriminator_layers": 3,
    "brnn": true,
    "timedistributed": true,
    "init_scalar": 0.05,
    "num_layers": 1,
    "unif": 0.25,
    "multi_gpu": true,
    "gpu_ids": [
        0,
        1,
        2,
        3
    ],
    "gradient_clipping": true,
    "max_norm": 1.0,
    "weight_decay": 0.0,
    "load_checkpoint": true,
    "use_pretrained_embeddings": true,
    "train_embeddings": true,
    "adaptive_dropout": false,
    "finetune": false,
    "max_iter": null,
    "nepochs": 50,
    "dropout": 0.5,
    "word_dropout": 0.5,
    "lstm_dropout": 0.5,
    "locked_dropout": 0.5,
    "batch_size": 64,
    "nepoch_no_imprv": 20,
    "nchkp_no_imprv": 30,
    "hidden_size": 1024,
    "subsampling": 0.0001,
    "class_weight": "uniform",
    "optim": "adam",
    "eval_steps": 1000,
    "lr": 0.001,
    "lr_decay": 0.5,
    "beta1": 0.0,
    "beta2": 0.98,
    "eps": 1e-08,
    "patience": 20,
    "scheduler": "ReduceLROnPlateau",
    "gamma": 0.99995,
    "pool_type": "max_pool",
    "dynamic_pool_size": 20,
    "wbatchsize": 3000,
    "wbatchsize_unlabel": 3000,
    "lambda_clf": 1.0,
    "lambda_ae": 0.0,
    "lambda_at": 1.0,
    "lambda_vat": 1.0,
    "lambda_entropy": 1.0,
    "inc_unlabeled_loss": true,
    "unlabeled_loss_type": "AvgTrainUnlabel",
    "perturb_norm_length": 5.0,
    "max_embedding_norm": null,
    "normalize_embedding": false,
    "add_noise": false,
    "noise_dropout": 0.1,
    "random_permutation": 3,
    "debug": true,
    "report_every": 100,
    "input": "temp/aclImdbSimple_pretrained_mixed/data",
    "save_data": "demo",
    "output_path": "temp/aclImdbSimple_pretrained_mixed/model",
    "exp_name": "aclImdbSimple_pretrained_mixed",
    "corpus": "aclImdb_tok",
    "model_file": "aclImdbSimple_pretrained_mixed.pt",
    "log_path": "temp/aclImdbSimple_pretrained_mixed/model/log_2019-04-03-03-05-45_time-aclImdbSimple_pretrained_mixed_rand_566.txt"
}
Loading pre-trained word vectors
/data/users/yuanhaoda/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/rnn.py:46: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.5 and num_layers=1
  "num_layers={}".format(dropout, num_layers))
/data/users/yuanhaoda/classify/ssl_text_classification/model.py:60: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  weight_init.xavier_uniform(l.weight.data)
Corpus: aclImdb_tok
Pytorch Model
Embedder(
  (embedder): Embedding(114419, 300, padding_idx=0)
  (word_dropout): Dropout(p=0.5)
)
LSTMEncoder(
  (dropout): Dropout(p=0.5)
  (lstm_encoder): Encoder(
    (rnn): LSTM(300, 512, dropout=0.5, bidirectional=True)
  )
  (lstm_dropout): Dropout(p=0.5)
)
Classifier(
  (clf): Linear(in_features=1024, out_features=2, bias=True)
)
SequenceCriteria(
  (criteria): CrossEntropyLoss()
)
Start training
Epoch 1 out of 50
Traceback (most recent call last):
  File "main.py", line 50, in <module>
    object(train_data, dev_data, test_data, unlabel_data)
  File "/data/users/yuanhaoda/classify/ssl_text_classification/training.py", line 217, in __call__
    self._train(train, dev, unlabel)
  File "/data/users/yuanhaoda/classify/ssl_text_classification/training.py", line 465, in _train
    accuracy = self._run_epoch(train_data, dev_data, unlabel_data)
  File "/data/users/yuanhaoda/classify/ssl_text_classification/training.py", line 258, in _run_epoch
    train_batch)
  File "/data/users/yuanhaoda/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/users/yuanhaoda/classify/ssl_text_classification/model.py", line 282, in forward
    batch.sent_len)
  File "/data/users/yuanhaoda/classify/ssl_text_classification/model.py", line 277, in encode_sent
    self.config)(self.lstm_encoder)
  File "/data/users/yuanhaoda/classify/ssl_text_classification/model.py", line 175, in __init__
    self.sent_packed = nn.utils.rnn.pack_padded_sequence(sent, sent_len)
  File "/data/users/yuanhaoda/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/utils/rnn.py", line 147, in pack_padded_sequence
    lengths = torch.as_tensor(lengths, dtype=torch.int64)
ValueError: some of the strides of a given numpy array are negative. This is currently not supported, but will be added in future releases.

**Comment by DevSinghSachan** [comment]
Could you try to make sure that you have correctly installed the dependencies including their appropriate versions and then run the script.

**Comment by guotong1988** [comment]
Same problem. Same stacktrace.

**Comment by DevSinghSachan** [comment]
I think, this issue is solved by the latest PR. Thanks!
Feel free to reopen if not solved.
