### ISSUE TITLE
AE model

### ISSUE THREAD

**Issue by paulpaul91** [DevSinghSachan/ssl_text_classification#3]
can you tell me the ae model?
There are four loss functions in this paper. but the code has five loss.Can you tell me why?

**Comment by DevSinghSachan** [comment]
We also performed experiments by including AE as an optional loss but had varying results depending on the datasets. We chose not to include those results in the final version of our paper.

**Comment by paulpaul91** [comment]
> We also performed experiments by including AE as an optional loss but had varying results depending on the datasets. We chose not to include those results in the final version of our paper.
thank you

**Comment by guotong1988** [comment]
Same question. What is AEModel?

**Comment by guotong1988** [comment]
AEModel's AE stand for what?

**Comment by DevSinghSachan** [comment]
AE is actually denoising auto-encoder model

**Comment by guotong1988** [comment]
Thank you !
